version: '2'

services:
  golang:
    container_name: gotainer_glide_ubuntu
    build:
      context: .
      args:
        project_name: project
    entrypoint: /go/bin/project
    env_file: environment.env
    image: golang_glide_ubuntu
    volumes:
      - ./:/go
    ports:
      - "8866:8888"
