FROM golang
 
# Some convenient tools
RUN apt-get update && apt-get -y install vim

# environment variables
ARG folder

# Go environment
ADD ./src/project /go/src/project
RUN go install project
ENTRYPOINT /go/bin/project

EXPOSE 8888 
