version: '2'

services:
  golang:
    container_name: gotainer_glide
    build:
      context: .
      dockerfile: Dockerfile-glide
      args:
        folder: project
    env_file: environment.env
    image: golang_glide_image
    volumes:
      - ./:/go
    ports:
      - "8888:8888"
    # entrypoint: /go/bin/project
